server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Octavio-Augusto-vsc/configCloud

eureka:
  instance:
    hostname: localhost
